IF COL_LENGTH('TB_SOLICITACAO', 'nota_prazos') IS NULL
    ALTER TABLE TB_SOLICITACAO ADD nota_prazos INT NULL;

IF COL_LENGTH('TB_SOLICITACAO', 'nota_qualidade') IS NULL
    ALTER TABLE TB_SOLICITACAO ADD nota_qualidade INT NULL;

IF COL_LENGTH('TB_SOLICITACAO', 'nota_atendimento') IS NULL
    ALTER TABLE TB_SOLICITACAO ADD nota_atendimento INT NULL;

IF COL_LENGTH('TB_SOLICITACAO', 'feedback_comentario') IS NULL
    ALTER TABLE TB_SOLICITACAO ADD feedback_comentario VARCHAR(2000) NULL;
